/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    gebruikers: GebruikerAuthOperations;
  };
  blocks: {};
  collections: {
    paginas: Pagina;
    diensten: Diensten;
    methodes: Methode;
    publicaties: Publicaty;
    media: Media;
    gebruikers: Gebruiker;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    diensten: DienstenSelect<false> | DienstenSelect<true>;
    methodes: MethodesSelect<false> | MethodesSelect<true>;
    publicaties: PublicatiesSelect<false> | PublicatiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gebruikers: GebruikersSelect<false> | GebruikersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigatie: Navigatie;
    footer: Footer;
  };
  globalsSelect: {
    navigatie: NavigatieSelect<false> | NavigatieSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Gebruiker;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface GebruikerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titel: string;
  /**
   * Alleen door admin te wijzigen — links en navigatie hangen hieraan.
   */
  slug: string;
  hero: {
    type: 'homeHero' | 'paginaHero' | 'kopHeader';
    kop?: {
      voor?: string | null;
      accent?: string | null;
      na?: string | null;
    };
    subtitel?: string | null;
    introZin?: string | null;
    pillLabel?: string | null;
    foto: number | Media;
    fotoFocus?:
      | (
          | 'center 12%'
          | 'center 15%'
          | 'center 20%'
          | 'center 22%'
          | 'center 25%'
          | 'center 28%'
          | 'center 30%'
          | 'center center'
        )
      | null;
    cta?: {
      label?: string | null;
      doel?:
        | (
            | '/'
            | '/methodiek'
            | '/aanbod'
            | '/coaching'
            | '/mentorschap'
            | '/opleidingen'
            | '/organisaties'
            | '/workshops'
            | '/wininstituut'
            | '/weerbaarheidsmentor'
            | '/kennisinstituut'
            | '/ontwikkellijn'
            | '/kennismaking'
          )
        | null;
    };
    secundaireCta?: {
      label?: string | null;
      doel?:
        | (
            | '/'
            | '/methodiek'
            | '/aanbod'
            | '/coaching'
            | '/mentorschap'
            | '/opleidingen'
            | '/organisaties'
            | '/workshops'
            | '/wininstituut'
            | '/weerbaarheidsmentor'
            | '/kennisinstituut'
            | '/ontwikkellijn'
            | '/kennismaking'
          )
        | null;
    };
  };
  layout?:
    | (
        | IntroSplitBlok
        | KaartenGridBlok
        | QuoteBandBlok
        | HerkenningSplitBlok
        | OntwikkellijnBandBlok
        | DienstenKaartenBlok
        | TrajectenKaartenBlok
        | ChecklistKaartBlok
        | ContrastKolommenBlok
        | PijlersDrieluikBlok
        | FotoLabelsSplitBlok
        | DonkerPaneelBlok
        | BentoGridBlok
        | GenummerdeLijstBlok
        | BadgesRijBlok
        | TabelSectieBlok
        | ProgressieCirkelsBlok
        | FotoKaartenRijBlok
        | PublicatiesGridBlok
        | CalloutBandBlok
        | InvesteringBlok
        | VerwachtingenLijstBlok
        | AgendaPlaceholderBlok
        | BookingBlok
        | CtaBandBlok
      )[]
    | null;
  metaTitel?: string | null;
  metaOmschrijving?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload hier foto’s. Alt-tekst is verplicht (toegankelijkheid + vindbaarheid). Gebruik het focuspunt om te bepalen wat in beeld blijft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    kaart?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSplitBlok".
 */
export interface IntroSplitBlok {
  stijl:
    | 'homeIntro'
    | 'quoteTekstFoto'
    | 'oorsprong'
    | 'fotoLabelKaart'
    | 'cirkelfoto'
    | 'wortels'
    | 'miniKaarten'
    | 'featureKaarten'
    | 'tweeKolomsTekst'
    | 'fullBleedFoto'
    | 'gecentreerd';
  eyebrow?: string | null;
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  quote?: string | null;
  alineas?:
    | {
        tekst: string;
        id?: string | null;
      }[]
    | null;
  verderLinks?:
    | {
        link?: {
          label?: string | null;
          doel?:
            | (
                | '/'
                | '/methodiek'
                | '/aanbod'
                | '/coaching'
                | '/mentorschap'
                | '/opleidingen'
                | '/organisaties'
                | '/workshops'
                | '/wininstituut'
                | '/weerbaarheidsmentor'
                | '/kennisinstituut'
                | '/ontwikkellijn'
                | '/kennismaking'
              )
            | null;
        };
        id?: string | null;
      }[]
    | null;
  blockquote?: string | null;
  citeLabel?: string | null;
  foto?: (number | null) | Media;
  fotoKaartTekst?: string | null;
  tegels?:
    | {
        titel?: string | null;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  bullets?:
    | {
        label?: string | null;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'introSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KaartenGridBlok".
 */
export interface KaartenGridBlok {
  stijl: 'domeinen' | 'zonderIcoon' | 'waardedriehoek' | 'domeinenRond' | 'methodes' | 'witKader' | 'voorWieTegels';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  introZin?: string | null;
  afsluitQuote?: string | null;
  items?:
    | {
        titel?: string | null;
        omschrijving?: string | null;
        link?: {
          label?: string | null;
          doel?:
            | (
                | '/'
                | '/methodiek'
                | '/aanbod'
                | '/coaching'
                | '/mentorschap'
                | '/opleidingen'
                | '/organisaties'
                | '/workshops'
                | '/wininstituut'
                | '/weerbaarheidsmentor'
                | '/kennisinstituut'
                | '/ontwikkellijn'
                | '/kennismaking'
              )
            | null;
        };
        icoon?: ('fysiek' | 'mentaal' | 'sociaal' | 'emotioneel' | 'ster' | 'geen') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'kaartenGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBandBlok".
 */
export interface QuoteBandBlok {
  stijl: 'navyBand' | 'kaartGoudrand' | 'gecentreerdLicht' | 'statementRand' | 'navyTekst';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  quote: string;
  accentDeel?: string | null;
  toonWaardedriehoek?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quoteBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HerkenningSplitBlok".
 */
export interface HerkenningSplitBlok {
  stijl: 'herkenning' | 'lijfBrein' | 'regie' | 'labelBullets';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  introZin?: string | null;
  alinea?: string | null;
  items?:
    | {
        titel?: string | null;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  afsluiter?: string | null;
  cta?: {
    label?: string | null;
    doel?:
      | (
          | '/'
          | '/methodiek'
          | '/aanbod'
          | '/coaching'
          | '/mentorschap'
          | '/opleidingen'
          | '/organisaties'
          | '/workshops'
          | '/wininstituut'
          | '/weerbaarheidsmentor'
          | '/kennisinstituut'
          | '/ontwikkellijn'
          | '/kennismaking'
        )
      | null;
  };
  foto?: (number | null) | Media;
  fotoQuote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'herkenningSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OntwikkellijnBandBlok".
 */
export interface OntwikkellijnBandBlok {
  stijl: 'navyKaarten' | 'bronzeKaarten' | 'cirkels' | 'verspringend' | 'uitgebreid';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  eyebrow?: string | null;
  introZin?: string | null;
  fasen?:
    | {
        omschrijving: string;
        subItems?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ontwikkellijnBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DienstenKaartenBlok".
 */
export interface DienstenKaartenBlok {
  info?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dienstenKaarten';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrajectenKaartenBlok".
 */
export interface TrajectenKaartenBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  kaarten?:
    | {
        label?: string | null;
        titel?: string | null;
        omschrijving?: string | null;
        dienst?: (number | null) | Diensten;
        prijsTekst?: string | null;
        donker?: boolean | null;
        link?: {
          label?: string | null;
          doel?:
            | (
                | '/'
                | '/methodiek'
                | '/aanbod'
                | '/coaching'
                | '/mentorschap'
                | '/opleidingen'
                | '/organisaties'
                | '/workshops'
                | '/wininstituut'
                | '/weerbaarheidsmentor'
                | '/kennisinstituut'
                | '/ontwikkellijn'
                | '/kennismaking'
              )
            | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trajectenKaarten';
}
/**
 * Eén plek voor prijzen en dienstteksten — een wijziging hier werkt automatisch door op elke pagina waar de dienst getoond wordt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten".
 */
export interface Diensten {
  id: number;
  naam: string;
  route:
    | '/'
    | '/methodiek'
    | '/aanbod'
    | '/coaching'
    | '/mentorschap'
    | '/opleidingen'
    | '/organisaties'
    | '/workshops'
    | '/wininstituut'
    | '/weerbaarheidsmentor'
    | '/kennisinstituut'
    | '/ontwikkellijn'
    | '/kennismaking';
  kaartOmschrijving: string;
  prijsLabel: string;
  prijsDetail?: string | null;
  linkTekst?: string | null;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistKaartBlok".
 */
export interface ChecklistKaartBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  items?:
    | {
        tekst: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklistKaart';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContrastKolommenBlok".
 */
export interface ContrastKolommenBlok {
  kolomLinks?: {
    koptitel?: string | null;
    items?:
      | {
          titel?: string | null;
          omschrijving?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  kolomRechts?: {
    koptitel?: string | null;
    items?:
      | {
          titel?: string | null;
          omschrijving?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contrastKolommen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PijlersDrieluikBlok".
 */
export interface PijlersDrieluikBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  introZin?: string | null;
  pijlers?:
    | {
        titel?: string | null;
        punten?:
          | {
              tekst?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pijlersDrieluik';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FotoLabelsSplitBlok".
 */
export interface FotoLabelsSplitBlok {
  stijl: 'incompany' | 'begeleidingsvormen';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  alinea?: string | null;
  items?:
    | {
        groot?: string | null;
        klein?: string | null;
        id?: string | null;
      }[]
    | null;
  foto?: (number | null) | Media;
  badgeTekst?: string | null;
  fotoQuote?: string | null;
  link?: {
    label?: string | null;
    doel?:
      | (
          | '/'
          | '/methodiek'
          | '/aanbod'
          | '/coaching'
          | '/mentorschap'
          | '/opleidingen'
          | '/organisaties'
          | '/workshops'
          | '/wininstituut'
          | '/weerbaarheidsmentor'
          | '/kennisinstituut'
          | '/ontwikkellijn'
          | '/kennismaking'
        )
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'fotoLabelsSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonkerPaneelBlok".
 */
export interface DonkerPaneelBlok {
  stijl: 'bronzeSkew' | 'navyCentered';
  eyebrow?: string | null;
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  alinea?: string | null;
  kolommen?:
    | {
        titel?: string | null;
        tekst?: string | null;
        items?:
          | {
              tekst?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'donkerPaneel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoGridBlok".
 */
export interface BentoGridBlok {
  stijl: 'opleidingen' | 'watHetBrengt';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  subLabel?: string | null;
  kaarten?:
    | {
        titel?: string | null;
        omschrijving?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GenummerdeLijstBlok".
 */
export interface GenummerdeLijstBlok {
  stijl: 'resultaat' | 'leeraanpak' | 'oplevert' | 'fundamentLinks';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  accentregel?: string | null;
  alinea?: string | null;
  items?:
    | {
        titel?: string | null;
        omschrijving?: string | null;
        link?: {
          label?: string | null;
          doel?:
            | (
                | '/'
                | '/methodiek'
                | '/aanbod'
                | '/coaching'
                | '/mentorschap'
                | '/opleidingen'
                | '/organisaties'
                | '/workshops'
                | '/wininstituut'
                | '/weerbaarheidsmentor'
                | '/kennisinstituut'
                | '/ontwikkellijn'
                | '/kennismaking'
              )
            | null;
        };
        id?: string | null;
      }[]
    | null;
  foto?: (number | null) | Media;
  kaderQuote?: string | null;
  kaderOnderschrift?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'genummerdeLijst';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BadgesRijBlok".
 */
export interface BadgesRijBlok {
  stijl: 'expertise' | 'rollen' | 'doelgroepen';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  alinea?: string | null;
  foto?: (number | null) | Media;
  badges?:
    | {
        label?: string | null;
        subLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'badgesRij';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabelSectieBlok".
 */
export interface TabelSectieBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  kolomkop1?: string | null;
  kolomkop2?: string | null;
  rijen?:
    | {
        kolom1?: string | null;
        kolom2?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabelSectie';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgressieCirkelsBlok".
 */
export interface ProgressieCirkelsBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  afsluitQuote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'progressieCirkels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FotoKaartenRijBlok".
 */
export interface FotoKaartenRijBlok {
  kaarten?:
    | {
        titel?: string | null;
        omschrijving?: string | null;
        linkTekst?: string | null;
        link?: {
          label?: string | null;
          doel?:
            | (
                | '/'
                | '/methodiek'
                | '/aanbod'
                | '/coaching'
                | '/mentorschap'
                | '/opleidingen'
                | '/organisaties'
                | '/workshops'
                | '/wininstituut'
                | '/weerbaarheidsmentor'
                | '/kennisinstituut'
                | '/ontwikkellijn'
                | '/kennismaking'
              )
            | null;
        };
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fotoKaartenRij';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PublicatiesGridBlok".
 */
export interface PublicatiesGridBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'publicatiesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBandBlok".
 */
export interface CalloutBandBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  alinea?: string | null;
  knopLabel?: string | null;
  externeUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'calloutBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InvesteringBlok".
 */
export interface InvesteringBlok {
  eyebrow?: string | null;
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  dienst?: (number | null) | Diensten;
  prijsZin?: string | null;
  rationale?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'investeringBlok';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerwachtingenLijstBlok".
 */
export interface VerwachtingenLijstBlok {
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  items?:
    | {
        titel?: string | null;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'verwachtingenLijst';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgendaPlaceholderBlok".
 */
export interface AgendaPlaceholderBlok {
  kopTekst?: string | null;
  tekst?: string | null;
  statusLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agendaPlaceholder';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingBlok".
 */
export interface BookingBlok {
  /**
   * De beschikbaarheid en de formuliervelden komen uit het platform-dashboard — hier stel je alleen de introtekst in.
   */
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'booking';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlok".
 */
export interface CtaBandBlok {
  stijl: 'navy' | 'goud' | 'cream' | 'creamKader' | 'charcoal' | 'witKaart' | 'mentorschap';
  kop?: {
    voor?: string | null;
    accent?: string | null;
    na?: string | null;
  };
  alinea?: string | null;
  cta?: {
    label?: string | null;
    doel?:
      | (
          | '/'
          | '/methodiek'
          | '/aanbod'
          | '/coaching'
          | '/mentorschap'
          | '/opleidingen'
          | '/organisaties'
          | '/workshops'
          | '/wininstituut'
          | '/weerbaarheidsmentor'
          | '/kennisinstituut'
          | '/ontwikkellijn'
          | '/kennismaking'
        )
      | null;
  };
  secundaireCta?: {
    label?: string | null;
    doel?:
      | (
          | '/'
          | '/methodiek'
          | '/aanbod'
          | '/coaching'
          | '/mentorschap'
          | '/opleidingen'
          | '/organisaties'
          | '/workshops'
          | '/wininstituut'
          | '/weerbaarheidsmentor'
          | '/kennisinstituut'
          | '/ontwikkellijn'
          | '/kennismaking'
        )
      | null;
  };
  secundaireTekst?: string | null;
  disclaimer?: string | null;
  contactTitel?: string | null;
  contactSub?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * Het integratieve palet op de Methodiek-pagina. Je mag methodes toevoegen of verwijderen — het raster past zich aan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "methodes".
 */
export interface Methode {
  id: number;
  titel: string;
  omschrijving: string;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * De inzichten & publicaties op de Kennisinstituut-pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaties".
 */
export interface Publicaty {
  id: number;
  titel: string;
  themaLabel: string;
  foto: number | Media;
  inhoud?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers".
 */
export interface Gebruiker {
  id: number;
  naam: string;
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'gebruikers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'diensten';
        value: number | Diensten;
      } | null)
    | ({
        relationTo: 'methodes';
        value: number | Methode;
      } | null)
    | ({
        relationTo: 'publicaties';
        value: number | Publicaty;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gebruikers';
        value: number | Gebruiker;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'gebruikers';
    value: number | Gebruiker;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titel?: T;
  slug?: T;
  hero?:
    | T
    | {
        type?: T;
        kop?:
          | T
          | {
              voor?: T;
              accent?: T;
              na?: T;
            };
        subtitel?: T;
        introZin?: T;
        pillLabel?: T;
        foto?: T;
        fotoFocus?: T;
        cta?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        secundaireCta?:
          | T
          | {
              label?: T;
              doel?: T;
            };
      };
  layout?:
    | T
    | {
        introSplit?: T | IntroSplitBlokSelect<T>;
        kaartenGrid?: T | KaartenGridBlokSelect<T>;
        quoteBand?: T | QuoteBandBlokSelect<T>;
        herkenningSplit?: T | HerkenningSplitBlokSelect<T>;
        ontwikkellijnBand?: T | OntwikkellijnBandBlokSelect<T>;
        dienstenKaarten?: T | DienstenKaartenBlokSelect<T>;
        trajectenKaarten?: T | TrajectenKaartenBlokSelect<T>;
        checklistKaart?: T | ChecklistKaartBlokSelect<T>;
        contrastKolommen?: T | ContrastKolommenBlokSelect<T>;
        pijlersDrieluik?: T | PijlersDrieluikBlokSelect<T>;
        fotoLabelsSplit?: T | FotoLabelsSplitBlokSelect<T>;
        donkerPaneel?: T | DonkerPaneelBlokSelect<T>;
        bentoGrid?: T | BentoGridBlokSelect<T>;
        genummerdeLijst?: T | GenummerdeLijstBlokSelect<T>;
        badgesRij?: T | BadgesRijBlokSelect<T>;
        tabelSectie?: T | TabelSectieBlokSelect<T>;
        progressieCirkels?: T | ProgressieCirkelsBlokSelect<T>;
        fotoKaartenRij?: T | FotoKaartenRijBlokSelect<T>;
        publicatiesGrid?: T | PublicatiesGridBlokSelect<T>;
        calloutBand?: T | CalloutBandBlokSelect<T>;
        investeringBlok?: T | InvesteringBlokSelect<T>;
        verwachtingenLijst?: T | VerwachtingenLijstBlokSelect<T>;
        agendaPlaceholder?: T | AgendaPlaceholderBlokSelect<T>;
        booking?: T | BookingBlokSelect<T>;
        ctaBand?: T | CtaBandBlokSelect<T>;
      };
  metaTitel?: T;
  metaOmschrijving?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSplitBlok_select".
 */
export interface IntroSplitBlokSelect<T extends boolean = true> {
  stijl?: T;
  eyebrow?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  quote?: T;
  alineas?:
    | T
    | {
        tekst?: T;
        id?: T;
      };
  verderLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        id?: T;
      };
  blockquote?: T;
  citeLabel?: T;
  foto?: T;
  fotoKaartTekst?: T;
  tegels?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  bullets?:
    | T
    | {
        label?: T;
        tekst?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KaartenGridBlok_select".
 */
export interface KaartenGridBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  introZin?: T;
  afsluitQuote?: T;
  items?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        link?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        icoon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBandBlok_select".
 */
export interface QuoteBandBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  quote?: T;
  accentDeel?: T;
  toonWaardedriehoek?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HerkenningSplitBlok_select".
 */
export interface HerkenningSplitBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  introZin?: T;
  alinea?: T;
  items?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  afsluiter?: T;
  cta?:
    | T
    | {
        label?: T;
        doel?: T;
      };
  foto?: T;
  fotoQuote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OntwikkellijnBandBlok_select".
 */
export interface OntwikkellijnBandBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  eyebrow?: T;
  introZin?: T;
  fasen?:
    | T
    | {
        omschrijving?: T;
        subItems?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DienstenKaartenBlok_select".
 */
export interface DienstenKaartenBlokSelect<T extends boolean = true> {
  info?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrajectenKaartenBlok_select".
 */
export interface TrajectenKaartenBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  kaarten?:
    | T
    | {
        label?: T;
        titel?: T;
        omschrijving?: T;
        dienst?: T;
        prijsTekst?: T;
        donker?: T;
        link?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistKaartBlok_select".
 */
export interface ChecklistKaartBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  items?:
    | T
    | {
        tekst?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContrastKolommenBlok_select".
 */
export interface ContrastKolommenBlokSelect<T extends boolean = true> {
  kolomLinks?:
    | T
    | {
        koptitel?: T;
        items?:
          | T
          | {
              titel?: T;
              omschrijving?: T;
              id?: T;
            };
      };
  kolomRechts?:
    | T
    | {
        koptitel?: T;
        items?:
          | T
          | {
              titel?: T;
              omschrijving?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PijlersDrieluikBlok_select".
 */
export interface PijlersDrieluikBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  introZin?: T;
  pijlers?:
    | T
    | {
        titel?: T;
        punten?:
          | T
          | {
              tekst?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FotoLabelsSplitBlok_select".
 */
export interface FotoLabelsSplitBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  alinea?: T;
  items?:
    | T
    | {
        groot?: T;
        klein?: T;
        id?: T;
      };
  foto?: T;
  badgeTekst?: T;
  fotoQuote?: T;
  link?:
    | T
    | {
        label?: T;
        doel?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonkerPaneelBlok_select".
 */
export interface DonkerPaneelBlokSelect<T extends boolean = true> {
  stijl?: T;
  eyebrow?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  alinea?: T;
  kolommen?:
    | T
    | {
        titel?: T;
        tekst?: T;
        items?:
          | T
          | {
              tekst?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoGridBlok_select".
 */
export interface BentoGridBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  subLabel?: T;
  kaarten?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GenummerdeLijstBlok_select".
 */
export interface GenummerdeLijstBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  accentregel?: T;
  alinea?: T;
  items?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        link?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        id?: T;
      };
  foto?: T;
  kaderQuote?: T;
  kaderOnderschrift?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BadgesRijBlok_select".
 */
export interface BadgesRijBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  alinea?: T;
  foto?: T;
  badges?:
    | T
    | {
        label?: T;
        subLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabelSectieBlok_select".
 */
export interface TabelSectieBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  kolomkop1?: T;
  kolomkop2?: T;
  rijen?:
    | T
    | {
        kolom1?: T;
        kolom2?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgressieCirkelsBlok_select".
 */
export interface ProgressieCirkelsBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  afsluitQuote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FotoKaartenRijBlok_select".
 */
export interface FotoKaartenRijBlokSelect<T extends boolean = true> {
  kaarten?:
    | T
    | {
        titel?: T;
        omschrijving?: T;
        linkTekst?: T;
        link?:
          | T
          | {
              label?: T;
              doel?: T;
            };
        foto?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PublicatiesGridBlok_select".
 */
export interface PublicatiesGridBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBandBlok_select".
 */
export interface CalloutBandBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  alinea?: T;
  knopLabel?: T;
  externeUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InvesteringBlok_select".
 */
export interface InvesteringBlokSelect<T extends boolean = true> {
  eyebrow?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  dienst?: T;
  prijsZin?: T;
  rationale?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerwachtingenLijstBlok_select".
 */
export interface VerwachtingenLijstBlokSelect<T extends boolean = true> {
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  items?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgendaPlaceholderBlok_select".
 */
export interface AgendaPlaceholderBlokSelect<T extends boolean = true> {
  kopTekst?: T;
  tekst?: T;
  statusLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookingBlok_select".
 */
export interface BookingBlokSelect<T extends boolean = true> {
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlok_select".
 */
export interface CtaBandBlokSelect<T extends boolean = true> {
  stijl?: T;
  kop?:
    | T
    | {
        voor?: T;
        accent?: T;
        na?: T;
      };
  alinea?: T;
  cta?:
    | T
    | {
        label?: T;
        doel?: T;
      };
  secundaireCta?:
    | T
    | {
        label?: T;
        doel?: T;
      };
  secundaireTekst?: T;
  disclaimer?: T;
  contactTitel?: T;
  contactSub?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diensten_select".
 */
export interface DienstenSelect<T extends boolean = true> {
  naam?: T;
  route?: T;
  kaartOmschrijving?: T;
  prijsLabel?: T;
  prijsDetail?: T;
  linkTekst?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "methodes_select".
 */
export interface MethodesSelect<T extends boolean = true> {
  titel?: T;
  omschrijving?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaties_select".
 */
export interface PublicatiesSelect<T extends boolean = true> {
  titel?: T;
  themaLabel?: T;
  foto?: T;
  inhoud?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        kaart?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gebruikers_select".
 */
export interface GebruikersSelect<T extends boolean = true> {
  naam?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * De teksten van het menu. De routes en volgorde zelf zijn onderdeel van de site-structuur en worden in code beheerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigatie".
 */
export interface Navigatie {
  id: number;
  /**
   * Volgorde: Methodiek · Aanbod · Coaching · Mentorschap · Opleidingen · Organisaties · Over WIN
   */
  hoofdmenu?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Volgorde: Kennisinstituut · De Mentor · Ontwikkellijn
   */
  meerMenu?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel: string;
  inloggenLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  adresRegel1: string;
  adresRegel2: string;
  mapsUrl: string;
  kvkNummer: string;
  copyrightSuffix: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigatie_select".
 */
export interface NavigatieSelect<T extends boolean = true> {
  hoofdmenu?:
    | T
    | {
        label?: T;
        id?: T;
      };
  meerMenu?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctaLabel?: T;
  inloggenLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  adresRegel1?: T;
  adresRegel2?: T;
  mapsUrl?: T;
  kvkNummer?: T;
  copyrightSuffix?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}